blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

# from post import views =>  url(r'^posts/$', views.postViews),
urlpatterns = [
    url(r'^', include('portfolio.urls')),
   # url(r'^', joins.views.home),
    url(r'^admin/', admin.site.urls),
    url(r'^post/', include('post.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  #  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name ='portfolio'

urlpatterns = [
   # /post/
    url(r'^$', views.home, name='home'),
]

post/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name ='post'

urlpatterns = [
   # /post/
    url(r'^$', views.postList, name='list'),

    #CRUD :

    url(r'^create/$', views.postCreate, name='create'),
    # /post/<id_of_object>
    url(r'^(?P<id>\d+)/$', views.postDetail, name='detail'), #regex for the id only the number dynamic url
    url(r'^(?P<id>\d+)/edit/$', views.postUpdate, name='update'),
    url(r'^(?P<id>\d+)/delete/$', views.postDelete, name='delete'),
#   url(r'^$', "<app_name>.views.<function_name>"), best method

]

joins/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Join(models.Model):

    username = models.CharField(max_length= 255)
    email = models.EmailField()
    update =models.DateTimeField(auto_now=True,auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __str__(self):
        return "{0}  -> {1}".format(self.username,self.email)

portfolio/models.py
from __future__ import unicode_literals
from django.utils.encoding import smart_unicode
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=250, null=True, blank=True)
    message = models.TextField()
    email= models.EmailField()
    time= models.DateTimeField(auto_now_add=True, auto_now=False)


    def __str__(self):
        return self.name +','+ smart_unicode(self.email)

post/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 250)
    image = models.FileField(upload_to='documents/',null=True,blank=True)
    content =models.TextField()
    update = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

    def __unicode__(self): # <=> __str__
        return self.title

    #class on the model order desc
    #make order data in the detail page
    class Meta:
        ordering = ['-id','-timestamp','-update']

portfolio/forms.py
from django import forms
from .models import Contact

# connect the form to the model (database)
# need class Meta => link with model
class ContactForm(forms.ModelForm):
    class Meta:
        model =Contact
        fields = [
            'name',
            'email',
            'message',
        ]

post/forms.py
from django import forms
from .models import Post

# connect the form to the model (database)
# need class Meta => link with model
class PostForm(forms.ModelForm):
    class Meta:
        model =Post
        fields = [
            'title',
            'content',
            'image',
        ]

joins/views.py
from django.shortcuts import render
from .form import JoinForm
# Create your views here.

def home(request):
    form = JoinForm()
    context = {"form": form}
    template = "index.html"
    return render(request,template,context)

portfolio/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Contact
from .forms import ContactForm
# Create your views here.
#
# def contact_create(request):
#     form = ContactForm(request.POST or None)
#     if form.is_valid():
#         instance = form.save(commit=True)
#         instance.save()
#     context = {
#         'form': form,
#     }
#     return render(request)

def home(request):
    context = {}
    return render(request,'index.html',context)

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,Http404
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post
from .forms import PostForm

# Create your views here.
# insert the CRUD method

#create a form
#get data from form and insert into database

def postCreate(request):
    #permission to the user to create,update or delete current post
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404 #redirect('post/index.html')
    forms = PostForm(request.POST or None, request.FILES or None)

    if forms.is_valid():
        instance = forms.save(commit=False)
        # print forms.cleaned_data.get('title')   print content field into the console
        instance.save()

    context = {
        'form': forms,
    }
    return render(request,'post/form.html', context)

def postDetail(request , id=None): # retrieve/ read / zoom
    # instance = get_object_or_404(<models_name, <element_of_table:'title','id'...>)
    instance = get_object_or_404(Post, id=id)
    context = {
        'instance': instance,
        'title': instance.title
    }
    return render(request,'post/details.html',context)

def postList(request): # list item / general
    querySet_list = Post.objects.all()

    # search bar
    q_search = request.GET.get('q_search')
    if q_search:
        querySet_list = Post.objects.filter(
            Q(title__icontains=q_search)|
            Q(content__icontains=q_search)
        ).distinct()
    #pagination
    paginator = Paginator(querySet_list, 3)  # Show 25 contacts per page
    page = request.GET.get('page')

    try:
        querySet = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        querySet = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        querySet = paginator.page(paginator.num_pages)





    context = {
        'object_list': querySet,
        'title': 'List'
    }
    return render(request,'post/index.html',context)



def postUpdate(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=id)

    forms = PostForm(request.POST or None, request.FILES or None,instance=instance)

    if forms.is_valid():
        instance = forms.save(commit=False)
        # print forms.cleaned_data.get('title')   print content field into the console
        instance.save()
        return redirect('post:detail', id=instance.id)

    context = {
        'instance': instance,
        'title': instance.title,
        'form': forms,
    }
    return render(request, 'post/form.html', context)


def postDelete(request, id=None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, id=id)
    instance.delete()
    return redirect('post:list')

portfolio/templates/index.html
 <!DOCTYPE html>
<html lang="fr">
<head>
	 <meta charset="utf-8">
	 <link href="https://s3.amazonaws.com/codecademy-content/projects/bootstrap.min.css" rel="stylesheet" />
	 <link href='https://fonts.googleapis.com/css?family=Roboto:500,300,700,400' rel='stylesheet' type='text/css'>
	 <!-- boostrap /google font => lien qui marche avec javaScript-->
	 <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
	<!--css file
	<link href="css/main.css" rel="stylesheet" />-->
</head>

<body > <!--ng-app => directive the scope => myApp module live wth my <body> -->
    <div class="header">
      <div class="container">
        <h1>My App</h1>
      </div>
    </div>

    <div class="main" >
      <div class="container">
		<h1>Test </h1>
		</div>
	</div>
	
	<!-- pub line keep it for next app -->
	<div class="footer">
      <div class="container">
        <h2>Available for iPhone and Android.</h2>
          <h3>Join us !!</h3>
          <form method="POST" action="#">  {% csrf_token %}
              {{ form.as_p }}
            <input type="submit" value="Submit" />
          </form>
        <img src="https://s3.amazonaws.com/codecademy-content/projects/shutterbugg/app-store.png" width="120px" />
        <img src="https://s3.amazonaws.com/codecademy-content/projects/shutterbugg/google-play.png" width="110px" />
      </div>
    </div>
</body>
</html> 

post/templates/post/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Title{% endblock  %}</title>

    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link href='{% static "post/blog.css" %}' rel="stylesheet">

  </head>
<body>

<!-- Facebook comment code -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

   <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'post:list' %}">Home display list</a>
          <a class="blog-nav-item" href="{% url 'post:create' %}">Create a new post (only admin)</a>
          <a class="blog-nav-item" href="#">Press</a>
          <a class="blog-nav-item" href="#">New hires</a>
          <a class="blog-nav-item" href="#">About</a>

          <form method="GET" action='' class="navbar-form navbar-right" role="search">
            <div class="form-group">
            <input type="text" class="form-control" name="q_search" value="{{request.GET.q_search}}" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
        </nav>
      </div>
    </div>

   <div class="container">
      <div class="row">
           <!--header-->
          {% block header %}{% endblock  %}

        <div class="col-sm-8 blog-main">
          <!--body-->
          {% block content %}{% endblock  %}

        </div><!-- /.blog-main -->
          {% block side-bar %}{% endblock  %}

      </div><!-- /.row -->
   </div><!-- /.container -->

  <footer class="blog-footer">
      <p>Blog template built for <a href="http://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>
<!-- Latest compiled and minified JavaScript -->
<script   src="https://code.jquery.com/jquery-2.2.4.js"   integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="   crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

post/templates/post/details.html
{% extends 'post/base.html' %}

{% block title %}Edit {% endblock %}


{% block content %}
    <div class="blog-item">
        <div  class="blog-post">
            <h2 class="blog-post-title">{{ title }}</h2>
                <p class="blog-post-meta">{{ instance.timestamp | timesince}}   By <a href="#">Mark</a></p>
                <p><div class="fb-like" data-href="{{request.build_absolute_uri}} data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
               <!-- https://developers.facebook.com/docs/plugins/" -->
                {% if instance.image %}
                    <img src="{{ instance.image.url }}" class="img-responsive"/>
                {% endif  %}
                <p>{{ instance.content | linebreaks}}</p>
        <hr>
            <p><div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div></p>
        </div>
    </div>
{% endblock %}

{% block side-bar %}
                    <span>{{request.build_absolute_uri}}</span>
 <div class="blog-item">
    <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
                  <div class="sidebar-module sidebar-module-inset">
                    <h4>About</h4>
                    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                  </div>
                  <div class="sidebar-module">
                    <h4>Archives</h4>
                    <ol class="list-unstyled">
                      <li><a href="#">March 2014</a></li>
                      <li><a href="#">February 2014</a></li>
                      <li><a href="#">January 2014</a></li>
                      <li><a href="#">December 2013</a></li>
                      <li><a href="#">November 2013</a></li>
                      <li><a href="#">October 2013</a></li>
                      <li><a href="#">September 2013</a></li>
                      <li><a href="#">August 2013</a></li>
                      <li><a href="#">July 2013</a></li>
                      <li><a href="#">June 2013</a></li>
                      <li><a href="#">May 2013</a></li>
                      <li><a href="#">April 2013</a></li>
                    </ol>
                  </div>
                  <div class="sidebar-module">
                    <h4>Elsewhere</h4>
                    <ol class="list-unstyled">
                      <li><a href="#">GitHub</a></li>
                      <li><a href="#">Twitter</a></li>
                      <li><a href="#">Facebook</a></li>
                    </ol>
                  </div>
            </div><!-- /.blog-sidebar -->
     </div>
{% endblock  %}

post/templates/post/form.html
{% extends 'post/base.html' %}
{% block title %}Form {% endblock %}

{% block content %}
<div class="blog-item">
    <form action="" method="post" enctype="multipart/form-data" >
        {%  csrf_token %}
        {{ form.as_ul}}
        <input type="submit" value="check Post"/>

    </form>
</div>
{% endblock content %}

post/templates/post/index.html
{% extends 'post/base.html' %}

{% block title %}Index | list{% endblock %}

{% block header %}
    <div class="blog-header">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">The official example template of creating a blog with Bootstrap.</p>
      </div>
{% endblock  %}

{% block content %}
    <div class="blog-post">

{% for obj in object_list %}
    <div class="row">
      <div class="col-sm-12 ">
        <div class="thumbnail">
            {% if obj.image %}
                <img src="{{ obj.image.url }}" class="img-responsive"/>
            {% endif %}
          <div class="caption">
            <h3><a href="{% url 'post:detail' id=obj.id %}"> {{ obj.title}}</a><small>  {{ obj.update | timesince}}</small></h3>
            <p>
                 {{ obj.content | linebreaks}}
                {{ obj.pk}}
            </p>
            <p><a href="{% url 'post:detail' id=obj.id %}" class="btn btn-primary" role="button">Details</a></p>
          </div>
        </div>
      </div>
    </div>
{% endfor %}
    </div>

<div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
            <a href="?page={{ object_list.previous_page_number }}{%if request.GET.q_search%}&q_search={{request.GET.q_search}}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
        </span>

        {% if object_list.has_next %}
            <a href="?page={{ object_list.next_page_number }}{%if request.GET.q_search%}&q_search={{request.GET.q_search}}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

{% endblock  %}
{% block side-bar %}
<div class="col-sm-3 col-sm-offset-1 blog-sidebar">
              <div class="sidebar-module sidebar-module-inset">
                <h4>About</h4>
                <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
              </div>
              <div class="sidebar-module">
                <h4>Archives</h4>
                <ol class="list-unstyled">
                  <li><a href="#">March 2014</a></li>
                  <li><a href="#">February 2014</a></li>
                  <li><a href="#">January 2014</a></li>
                  <li><a href="#">December 2013</a></li>
                  <li><a href="#">November 2013</a></li>
                  <li><a href="#">October 2013</a></li>
                  <li><a href="#">September 2013</a></li>
                  <li><a href="#">August 2013</a></li>
                  <li><a href="#">July 2013</a></li>
                  <li><a href="#">June 2013</a></li>
                  <li><a href="#">May 2013</a></li>
                  <li><a href="#">April 2013</a></li>
                </ol>
              </div>
              <div class="sidebar-module">
                <h4>Elsewhere</h4>
                <ol class="list-unstyled">
                  <li><a href="#">GitHub</a></li>
                  <li><a href="#">Twitter</a></li>
                  <li><a href="#">Facebook</a></li>
                </ol>
              </div>
        </div><!-- /.blog-sidebar -->
{% endblock  %}